# Development Configuration for Project Raven
# "Local development settings aligned with your current setup"

[server]
host = "127.0.0.1"
port = 50051
max_connections = 100
heartbeat_interval_seconds = 60
client_timeout_seconds = 120
enable_compression = false  # Easier debugging
max_message_size = 2097152  # 2MB

[database]
influx_url = "http://localhost:8086"
bucket = "crypto_dev"
org = "influx"
token = "admin-token-banana"  # Your current dev token
connection_pool_size = 5
connection_timeout_seconds = 30
write_timeout_seconds = 10
query_timeout_seconds = 60
retry_attempts = 1
retry_delay_ms = 2000
circuit_breaker_threshold = 10
circuit_breaker_timeout_seconds = 120

[data_processing]
snapshot_interval_ms = 100  # Slower for development
high_frequency_buffer_size = 1000
low_frequency_buffer_size = 100
private_data_buffer_size = 50
data_validation_enabled = true
sanitization_enabled = true
dead_letter_queue_size = 100

# Development retention policies - shorter retention
[retention_policies.high_frequency]
full_resolution_days = 1
downsampled_days = 3
archive_days = 7
auto_cleanup = true
compression_enabled = false

[retention_policies.low_frequency]
full_resolution_days = 7
downsampled_days = 14
archive_days = 30
auto_cleanup = true
compression_enabled = false

[retention_policies.private_data]
full_resolution_days = 3
downsampled_days = 7
archive_days = 14
auto_cleanup = true  # Auto cleanup in dev
compression_enabled = false

[retention_policies.system_logs]
full_resolution_days = 1
downsampled_days = 3
archive_days = 7
auto_cleanup = true
compression_enabled = false

# Development batching - smaller batches for easier debugging
[batching.database_writes]
size = 10
timeout_ms = 100
max_memory_mb = 10
compression_threshold = 5

[batching.client_broadcasts]
size = 5
timeout_ms = 50
max_memory_mb = 5
compression_threshold = 3

[batching.snapshot_captures]
size = 3
timeout_ms = 100
max_memory_mb = 3
compression_threshold = 2

[batching.metrics_collection]
size = 20
timeout_ms = 5000
max_memory_mb = 2
compression_threshold = 10

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 9091
tracing_enabled = true
log_level = "debug"  # Verbose logging for development
performance_monitoring = false  # Less overhead in dev