# Staging Configuration for Project Raven
# "The proving grounds before the final battle"

[server]
host = "0.0.0.0"
port = 50051
max_connections = 2000
heartbeat_interval_seconds = 20
client_timeout_seconds = 45
enable_compression = true
max_message_size = 6291456  # 6MB

[database]
influx_url = "http://influxdb-staging:8086"
database_name = "market_data_staging"
connection_pool_size = 25
connection_timeout_seconds = 8
write_timeout_seconds = 4
query_timeout_seconds = 20
retry_attempts = 3
retry_delay_ms = 750
circuit_breaker_threshold = 4
circuit_breaker_timeout_seconds = 45

[data_processing]
snapshot_interval_ms = 3  # Between dev and prod
high_frequency_buffer_size = 25000
low_frequency_buffer_size = 2500
private_data_buffer_size = 1250
data_validation_enabled = true
sanitization_enabled = true
dead_letter_queue_size = 2500

# Staging retention policies - moderate retention
[retention_policies.high_frequency]
full_resolution_days = 14
downsampled_days = 45
archive_days = 180
auto_cleanup = true
compression_enabled = true

[retention_policies.low_frequency]
full_resolution_days = 365  # 1 year
downsampled_days = 730      # 2 years
archive_days = 1095         # 3 years
auto_cleanup = true
compression_enabled = true

[retention_policies.private_data]
full_resolution_days = 180  # 6 months
downsampled_days = 365      # 1 year
archive_days = 730          # 2 years
auto_cleanup = false        # Manual cleanup for testing
compression_enabled = true

[retention_policies.system_logs]
full_resolution_days = 14
downsampled_days = 30
archive_days = 90
auto_cleanup = true
compression_enabled = true

# Staging batching - balanced for testing
[batching.database_writes]
size = 2500
timeout_ms = 3
max_memory_mb = 250
compression_threshold = 1250

[batching.client_broadcasts]
size = 250
timeout_ms = 1
max_memory_mb = 100
compression_threshold = 125

[batching.snapshot_captures]
size = 100
timeout_ms = 3
max_memory_mb = 50
compression_threshold = 50

[batching.metrics_collection]
size = 1000
timeout_ms = 750
max_memory_mb = 25
compression_threshold = 500

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 8080
tracing_enabled = true
log_level = "info"  # Balanced logging for staging
performance_monitoring = true