use crate::config::Settings;

pub use crate::service::spec::{client_host, ImbalanceBarSpec, ServiceSpec};

pub fn all_services(settings: &Settings) -> Vec<ServiceSpec> {
    vec![
        ServiceSpec {
            id: "binance_spot",
            display_name: "Binance Spot",
            bin_name: "binance_spot",
            log_name: "binance_spot",
            port: settings.server.port_binance_spot,
            args: vec![],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "binance_futures",
            display_name: "Binance Futures",
            bin_name: "binance_futures",
            log_name: "binance_futures",
            port: settings.server.port_binance_futures,
            args: vec![],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "binance_futures_klines",
            display_name: "Binance Futures Klines",
            bin_name: "binance_futures_klines",
            log_name: "binance_futures_klines",
            port: settings.server.port_binance_futures_klines,
            args: vec![],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "tibs_small",
            display_name: "Tibs (small)",
            bin_name: "raven_tibs",
            log_name: "tibs_small",
            port: settings.server.port_tibs_small,
            args: vec![],
            interval: Some("tib_small".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 100.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "tibs_large",
            display_name: "Tibs (large)",
            bin_name: "raven_tibs",
            log_name: "tibs_large",
            port: settings.server.port_tibs_large,
            args: vec![],
            interval: Some("tib_large".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 500.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "trbs_small",
            display_name: "Trbs (small)",
            bin_name: "raven_trbs",
            log_name: "trbs_small",
            port: settings.server.port_trbs_small,
            args: vec![],
            interval: Some("trb_small".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 100.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "trbs_large",
            display_name: "Trbs (large)",
            bin_name: "raven_trbs",
            log_name: "trbs_large",
            port: settings.server.port_trbs_large,
            args: vec![],
            interval: Some("trb_large".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 500.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "vibs_small",
            display_name: "Vibs (small)",
            bin_name: "raven_vibs",
            log_name: "vibs_small",
            port: settings.server.port_vibs_small,
            args: vec![],
            interval: Some("vib_small".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 100.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "vibs_large",
            display_name: "Vibs (large)",
            bin_name: "raven_vibs",
            log_name: "vibs_large",
            port: settings.server.port_vibs_large,
            args: vec![],
            interval: Some("vib_large".to_string()),
            imbalance: Some(ImbalanceBarSpec {
                initial_size: 250.0,
                initial_p_buy: 0.7,
                alpha_size: 0.7,
                alpha_imbl: 0.72,
                size_min_pct: Some(0.1),
                size_max_pct: Some(0.1),
            }),
        },
        ServiceSpec {
            id: "vpin",
            display_name: "VPIN",
            bin_name: "raven_vpin",
            log_name: "vpin",
            port: settings.server.port_vpin,
            args: vec![
                // Explicitly bind to the configured port (so multiple instances are possible).
                "--port".to_string(),
                settings.server.port_vpin.to_string(),
            ],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "tick_persistence",
            display_name: "Tick Persistence",
            bin_name: "tick_persistence",
            log_name: "tick_persistence",
            port: settings.server.port_tick_persistence,
            args: vec![],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "bar_persistence",
            display_name: "Bar Persistence",
            bin_name: "bar_persistence",
            log_name: "bar_persistence",
            port: settings.server.port_bar_persistence,
            args: vec![],
            interval: None,
            imbalance: None,
        },
        ServiceSpec {
            id: "kline_persistence",
            display_name: "Kline Persistence",
            bin_name: "kline_persistence",
            log_name: "kline_persistence",
            port: settings.server.port_kline_persistence,
            args: vec![],
            interval: None,
            imbalance: None,
        },
    ]
}
